version: '2'
services:
  datastore:
    container_name: datastore
    image: busybox
    volumes:
      - .:/app
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: merryx
      MYSQL_USER: root
      MYSQL_PASSWORD:
  app:
    container_name: app
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes_from:
      - datastore
    ports:
      - "3000:3000"
    links:
      - db
volumes:
  db_data:
