version: '2'
services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/charset.cnf:/etc/mysql/conf.d/charset.cnf
    environment:
      TZ: Asia/Tokyo
    env_file:
      - ./docker/db/.env
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    environment:
      TZ: Asia/Tokyo
    env_file:
      - ./docker/app/.env
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
volumes:
  db_data:

